### ISSUE TITLE
Inventory all trees in salt/fresh/control plots

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-seawater#1]
Needs to happen before they "turn on" in March.

- [x] Estimate how many trees (7500 m2 or 3/4 ha = ~500 trees?)
- [x] Order tree tags, stainless steel nails
- [x] Tag
- [x] Record DBH and live/dead
- [x] Record species (can happen later, in the growing season)

cc @stephpenn1

**Comment by bpbond** [comment]
And maybe install dendrometers?

**Comment by stegen** [comment]
How do you add the little check box?
Would like to add a task: "Making sure the plot corners are finalized"

**Comment by bpbond** [comment]
Hypen, space, and then "[ ]". There's also "Add a task list" in upper-right of GitHub text boxes.

**Comment by stegen** [comment]
- [] Making sure the plot corners are finalized

**Comment by bpbond** [comment]
Since that is necessary before the inventory, I'm going to assign this to you @stegen for now.
